kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."
  
steps:
- name: build
  image: maven:3-jdk-8
  commands:
    - "mvn package -B" 

- name: publish  
  image: plugins/ecr
  settings:
    repo: suraksha
    registry: 847370586410.dkr.ecr.us-east-1.amazonaws.com
    
- name: deploy 
  image: sailthru/sailthru-drone-eks
  cluster: terraform-eks-demo
  #service: my-service
  image_name: 847370586410.dkr.ecr.us-east-1.amazonaws.com/suraksha:latest
  aws_region: us-west-2
